[package]
name = "miniquad"
version = "0.3.0-alpha.41"
authors = ["not-fl3 <not.fl3@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
homepage = "https://github.com/not-fl3/miniquad"
repository = "https://github.com/not-fl3/miniquad"
description = """
Cross-platform window context and rendering library.
"""
readme="README.md"
keywords = ["graphics", "3D", "opengl", "gamedev", "windowing"]
categories = ["rendering::graphics-api"]

[features]
default = ["sapp-linux"]
kms = ["sapp-kms"]

# Optional log-rs like macros implementation
# disabled by default
log-impl = []

[target.'cfg(windows)'.dependencies]
sapp-windows = { path ="./native/sapp-windows", version = "=0.2.19" }

[target.'cfg(target_os = "linux")'.dependencies]
sapp-linux = { path ="./native/sapp-linux", version = "=0.1.13", optional = true }

sapp-kms = { path ="./native/sapp-kms", version = "=0.1.1", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
sapp-darwin = { path = "./native/sapp-darwin", version = "=0.1.6" }

[target.'cfg(target_os = "ios")'.dependencies]
sapp-ios = { path = "./native/sapp-ios", version = "=0.1.2" }

[target.'cfg(target_os = "android")'.dependencies]
sapp-android = { path = "./native/sapp-android", version = "=0.1.10" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
sapp-wasm = { path ="./native/sapp-wasm", version = "=0.1.26" }

[target.'cfg(not(any(target_os="linux", target_os="macos", target_os="android", target_os="ios", target_arch="wasm32", windows)))'.dependencies]
sapp-dummy = { path ="./native/sapp-dummy", version = "=0.1.5" }

[dev-dependencies]
glam = {version = "0.14", features = ["scalar-math"] }
quad-rand = "0.1"
