on: [push, pull_request]

name: Cross-compile

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, target: 'aarch64-unknown-linux-gnu' }
          - { os: ubuntu-latest, target: 'armv7-unknown-linux-gnueabihf' }
          - { os: ubuntu-latest, target: 'x86_64-unknown-linux-gnu' }
          - { os: ubuntu-latest, target: 'x86_64-pc-windows-gnu' }
          - { os: ubuntu-latest, target: 'wasm32-unknown-unknown' }
          - { os: macos-latest, target: 'x86_64-apple-darwin' }
          - { os: macos-latest, target: 'aarch64-apple-ios' }
          - { os: macos-latest, target: 'x86_64-apple-ios' }
          - { os: windows-latest, target: 'x86_64-pc-windows-msvc' }
        include:
          - os: ubuntu-latest
            packages: libx11-dev libxi-dev libgl1-mesa-dev gcc-mingw-w64

    steps:
      - uses: actions/checkout@v2
      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -yq --no-install-suggests --no-install-recommends install ${{ matrix.packages }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.config.target }}
          override: true
      - name: Workaround MinGW issue # https://github.com/rust-lang/rust/issues/47048
        if: runner.os == 'Linux' && matrix.config.target == 'x86_64-pc-windows-gnu'
        run: |
          sudo cp /usr/x86_64-w64-mingw32/lib/dllcrt2.o  ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/dllcrt2.o
          sudo cp /usr/x86_64-w64-mingw32/lib/crt2.o  ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/crt2.o
          echo "[target.x86_64-pc-windows-gnu]" >> ~/.cargo/config
          echo "linker = \"/usr/bin/x86_64-w64-mingw32-gcc\"" >> ~/.cargo/config
      - name: Setup aarch64
        if: matrix.config.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt install gcc-aarch64-linux-gnu
          echo "[target.aarch64-unknown-linux-gnu]" >> ~/.cargo/config
          echo "linker = \"aarch64-linux-gnu-gcc\"" >> ~/.cargo/config
      - name: Setup armv7
        if: matrix.config.target == 'armv7-unknown-linux-gnueabihf'
        run: |
          sudo apt install gcc-arm-linux-gnueabihf
          echo "[target.armv7-unknown-linux-gnueabihf]" >> ~/.cargo/config
          echo "linker = \"arm-linux-gnueabihf-gcc\"" >> ~/.cargo/config

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --target=${{ matrix.config.target }}

  android:
    name: Android
    runs-on: ubuntu-latest
    container: notfl3/cargo-apk
    steps:
      - uses: actions/checkout@v2
      
      - name: cargo quad-apk
        run: |
          cargo quad-apk build 
